/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicAcisDecisionRouteImport } from './routes/api/public/acis/decision'
import { Route as ApiPublicHooksGenerateBriefingsRouteImport } from './routes/api/public/hooks/generate-briefings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAcisDecisionRoute = ApiPublicAcisDecisionRouteImport.update({
  id: '/api/public/acis/decision',
  path: '/api/public/acis/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksGenerateBriefingsRoute =
  ApiPublicHooksGenerateBriefingsRouteImport.update({
    id: '/api/public/hooks/generate-briefings',
    path: '/api/public/hooks/generate-briefings',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/acis/decision': typeof ApiPublicAcisDecisionRoute
  '/api/public/hooks/generate-briefings': typeof ApiPublicHooksGenerateBriefingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/acis/decision': typeof ApiPublicAcisDecisionRoute
  '/api/public/hooks/generate-briefings': typeof ApiPublicHooksGenerateBriefingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/acis/decision': typeof ApiPublicAcisDecisionRoute
  '/api/public/hooks/generate-briefings': typeof ApiPublicHooksGenerateBriefingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/api/chat'
    | '/api/public/acis/decision'
    | '/api/public/hooks/generate-briefings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/api/chat'
    | '/api/public/acis/decision'
    | '/api/public/hooks/generate-briefings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/api/chat'
    | '/api/public/acis/decision'
    | '/api/public/hooks/generate-briefings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  LoginRoute: typeof LoginRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicAcisDecisionRoute: typeof ApiPublicAcisDecisionRoute
  ApiPublicHooksGenerateBriefingsRoute: typeof ApiPublicHooksGenerateBriefingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/acis/decision': {
      id: '/api/public/acis/decision'
      path: '/api/public/acis/decision'
      fullPath: '/api/public/acis/decision'
      preLoaderRoute: typeof ApiPublicAcisDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-briefings': {
      id: '/api/public/hooks/generate-briefings'
      path: '/api/public/hooks/generate-briefings'
      fullPath: '/api/public/hooks/generate-briefings'
      preLoaderRoute: typeof ApiPublicHooksGenerateBriefingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  LoginRoute: LoginRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicAcisDecisionRoute: ApiPublicAcisDecisionRoute,
  ApiPublicHooksGenerateBriefingsRoute: ApiPublicHooksGenerateBriefingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
